image: node:16

pipelines:
  branches:
    main:
      - step:
          name: Retype Build
          caches:
            - node
          script:
            - npm install retypeapp --global
            - retype build
            - git checkout -B retype
            - git add .
            - git commit -m "Retype build"
            - git push --set-upstream origin retype -f